<a href="https://colab.research.google.com/github/kcunni/OnePieceReddit/blob/main/NLTK.One_Piece_Research.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Analysis with NLTK

## What is NLTK?



[Natural Language Toolkit (NLTK)](https://www.nltk.org/index.html) provides classes and functions for text classification, tokenization, stemming, tagging, etc. It also provides access to over 50 copora and other lexical resources.

## Topics Being Covered

#### 1. Text Preprocessing
- Regular Expressions
- Tokenization
- Stop words

#### 2. Bag Of Words
- Word Vectors
- Word Counts
- TFIDF

# Setup

### Import Python Libraries

In [1]:
import re # module for Regular expressions
import os # module for using operating system
import nltk # natural language toolkit
import pandas as pd # Pandas package for data tables
import numpy as np # provides methods for vectors and mathematical functions

# Preprocess Text Data

Text preprocessing is the processing of cleaning text data to make it usable for analysis (or feed to a machine learning model). This process requires removal of 'noise' (unwanted characters or information), which may or may not include punctuation, emojis, line breaks, stop words. It may also involve the standardization of texts, such as lowercasing text, adjusting date-time formats, removing diacritics, stemming, or lemmatizing.

## 1. Understanding our text

In [3]:
df = pd.read_csv("reddit_onepiece.csv", encoding='utf-8') # loads the dataset CSV into a Pandas datatable

posts = df['content'] # saves the values from one column ('content') as a list under the variable 'post'

In [3]:
for post in posts.sample(10):
    print(post) # print's the text from the first post in our dataset
    print('\n\n\n')

nan




Folks, be ready to save this post because I am going to blow your mind with so many connections here that will, once elaborated, tell you what exactly is the One Piece and to an extent, it's connection to Luffy's dream.


Before you continue, please really think hard about the ramifications here by proceeding further. Once you read what the One Piece is, you will also smile and laugh 😄 just like Gol D Roger.

.

Do you really want to know? If yes, I will caution that I think the story is more enjoyable when the mystery of the One Piece is unsolved. You have been warned.





Scroll down to read.





















The way I will organize this post is by providing the connections and links to the clue about the One Piece. Then after demonstrating it, will reveal the actual Onepiece treasure and luffy's dream!



Connections: 

1. The ponyglyps are records historical information as well as music. Look at the ponyglyps, Oda obfuscated the musical "notes" embedded in them to tric

### What are some characters/patterns that might not be helpful for text analysis?



### What are some phrases that we might want to extract?

### Using Regular Expressions (regex)

Regular expressions are a way to match patterns in text in order to find, extract, and/or replace that pattern

<img src="assets/regex_cheatsheet.png" width='1200' height='600'>


[See this guide for a more comprehensive understanding of regular expressions](https://docs.python.org/3/howto/regex.html#regex-howto)

## Regex Exercises

In [4]:
ex_post = posts[0]
print(ex_post)

#One Piece: Episode 1101

##"The Strongest Form of Humanity! The Seraphim's Powers!"

###Watch now:

Streaming Site | Status
:--|:--
[Crunchyroll](https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece/)|**ONLINE**
*****
**Chapters adapted:** 
*****
Preview: [Episode 1102](http://www.fujitv.co.jp/b_hp/onepiece/index.html)

Don't forget to check out the official [Discord server](https://discord.gg/onepiece) to discuss this episode live with other One Piece fans!


In [5]:
# How would you remove astericks?

post_no_astx = re.sub(r'<REGEX PATTERN>', '<REGEX PATTERN>', ex_post)
print(post_no_astx)

#One Piece: Episode 1101

##"The Strongest Form of Humanity! The Seraphim's Powers!"

###Watch now:

Streaming Site | Status
:--|:--
[Crunchyroll](https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece/)|**ONLINE**
*****
**Chapters adapted:** 
*****
Preview: [Episode 1102](http://www.fujitv.co.jp/b_hp/onepiece/index.html)

Don't forget to check out the official [Discord server](https://discord.gg/onepiece) to discuss this episode live with other One Piece fans!


In [6]:
# Possible Answer
post_no_astx = re.sub(r'\* *', '', ex_post) # also removes the space after an asterick if there is one
print(post_no_astx)

#One Piece: Episode 1101

##"The Strongest Form of Humanity! The Seraphim's Powers!"

###Watch now:

Streaming Site | Status
:--|:--
[Crunchyroll](https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece/)|ONLINE

Chapters adapted:

Preview: [Episode 1102](http://www.fujitv.co.jp/b_hp/onepiece/index.html)

Don't forget to check out the official [Discord server](https://discord.gg/onepiece) to discuss this episode live with other One Piece fans!


In [7]:
# How would you extract links?

extracted_links = re.findall(r'<REGEX PATTERN>', ex_post)
print(extracted_links)


[]


In [8]:
# Possible Answer

extracted_links = re.findall(r'http.+(?=\))', ex_post)
print(extracted_links)

['https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece/', 'http://www.fujitv.co.jp/b_hp/onepiece/index.html', 'https://discord.gg/onepiece']


In [9]:
# How would you find the various mentions of "Leakers"?

luffy_mentions = re.findall(r'<REGEX PATTERN>', ex_post)
print(nvidia_mentions)

[]


In [11]:
# Possible Answer

luffy_mentions = re.findall(r'Luffy[\'s]* [A-Z][A-Za-z]+ *[A-Z]*[a-z]*', ex_post)
# what is returned isn't perfect since the first result contains the word 'has' which is unnecessary.
print(luffy_mentions)

[]


## Text Cleaning Example

In [12]:
ex_post2 = posts[20]
print(ex_post2)

I made this Boa cosplay only for fun but know i rly love it! I want to make in the future more characters but i think is a good start!💜 @tsudere_ 



In [16]:
# Remove numerical list

post_no_list = re.sub(r' *[0-9]+\. ', '', ex_post2)

print(post_no_list)

I made this Boa cosplay only for fun but know i rly love it! I want to make in the future more characters but i think is a good start!💜 @tsudere_ 



In [17]:
# Remove Astericks

post_no_astrx = re.sub(r'\*+', '', post_no_list)

print(post_no_astrx)

I made this Boa cosplay only for fun but know i rly love it! I want to make in the future more characters but i think is a good start!💜 @tsudere_ 



In [22]:
# remove back dashes and hyphens

post_no_spec_chars = re.sub(r'\\*[-~] *', '', post_no_astrx)

print(post_no_spec_chars)

I made this Boa cosplay only for fun but know i rly love it! I want to make in the future more characters but i think is a good start!💜 @tsudere_ 



In [18]:
# remove link markdown notation and links but keep link text

post_no_links = re.sub(r'\(.+\)', '', post_no_spec_chars) # removes links and their surrounding circle brackets
post_no_link_md = re.sub(r'\[|\]','', post_no_links)

print(post_no_link_md)

I made this Boa cosplay only for fun but know i rly love it! I want to make in the future more characters but i think is a good start!💜 @tsudere_ 



In [23]:
# let's put it all together

def clean_text(post):
    # print(post)
    post_no_list = re.sub(r' *[0-9]+\. ', '', post)
    post_no_astrx = re.sub(r'\*', '', post_no_list) # remove astricks
    # print(post_no_astrx)
    post_no_spec_chars = re.sub(r'[\\:\.~\-\|,]*', '', post_no_astrx)
    # print(post_no_spec_chars)
    post_no_links = re.sub(r'\(.+\)', '', post_no_spec_chars) # removes links and their surrounding circle brackets
    post_no_link_md = re.sub(r'\[|\]','', post_no_links)
    # print(post_no_link_md)
    post_no_breaks = re.sub(r'\n', '', post_no_link_md) # remove break lines
    # print(post_no_breaks)
    post_no_dbl_spaces = re.sub(r'  ', ' ', post_no_breaks)
    post_no_nums = re.sub(r'[0-9]+', '', post_no_dbl_spaces)
    post_lower = post_no_nums.lower() # make text all lowercase
    # print(post_lower)
    return post_lower

In [24]:
cleaned_post = clean_text(ex_post2)
print(cleaned_post)

i made this boa cosplay only for fun but know i rly love it! i want to make in the future more characters but i think is a good start!💜 @tsudere_ 


### Tokenization

Tokenization refers to splitting up text to a basic unit, normally called an n-gram. N-grams refer to tokens that consiste of 1+ words. A unigram is a one-word token (Ex: "text"), a bigram is a two-word token (Ex: "important text"), trigram is a three-word token (Ex: "very important text").

In [25]:
from nltk.tokenize import word_tokenize, sent_tokenize, PunktSentenceTokenizer
nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [26]:
print(ex_post2)

I made this Boa cosplay only for fun but know i rly love it! I want to make in the future more characters but i think is a good start!💜 @tsudere_ 



In [27]:
word_tokenize(ex_post2)

['I',
 'made',
 'this',
 'Boa',
 'cosplay',
 'only',
 'for',
 'fun',
 'but',
 'know',
 'i',
 'rly',
 'love',
 'it',
 '!',
 'I',
 'want',
 'to',
 'make',
 'in',
 'the',
 'future',
 'more',
 'characters',
 'but',
 'i',
 'think',
 'is',
 'a',
 'good',
 'start',
 '!',
 '💜',
 '@',
 'tsudere_']

In [28]:
tokenized_post = word_tokenize(cleaned_post)
print(tokenized_post)

['i', 'made', 'this', 'boa', 'cosplay', 'only', 'for', 'fun', 'but', 'know', 'i', 'rly', 'love', 'it', '!', 'i', 'want', 'to', 'make', 'in', 'the', 'future', 'more', 'characters', 'but', 'i', 'think', 'is', 'a', 'good', 'start', '!', '💜', '@', 'tsudere_']


### Stopwords

Stop words are a set of commonly used words that would not be helpful for analysis (Ex. a, the, is, are, etc.)

In [30]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [35]:
print(stopwords)

<WordListCorpusReader in '.../corpora/stopwords' (not loaded yet)>


In [75]:
# add custom stop word
updated_stopwords = stopwords.words('english')
new_stopwords = ['something', 'it', 'the', 'https', 'also', 'and', 'even', 'this', 'that', 'for','but','to', 'in']
updated_stopwords.extend(new_stopwords)

In [76]:
def remove_stopwords(post): # we want to pass in the tokenized post
    post_no_stop_words = [t for t in post.split() if t not in updated_stopwords]
    return post_no_stop_words

In [78]:
print(tokenized_post)

['i', 'made', 'this', 'boa', 'cosplay', 'only', 'for', 'fun', 'but', 'know', 'i', 'rly', 'love', 'it', '!', 'i', 'want', 'to', 'make', 'in', 'the', 'future', 'more', 'characters', 'but', 'i', 'think', 'is', 'a', 'good', 'start', '!', '💜', '@', 'tsudere_']


In [79]:
print(remove_stopwords(cleaned_post))

['made', 'boa', 'cosplay', 'fun', 'know', 'rly', 'love', 'it!', 'want', 'make', 'future', 'characters', 'think', 'good', 'start!💜', '@tsudere_']


## N-Grams

N-grams refer to collections of terms from a text that. For example, a series that is just term is a unigram, two words is a bigram, three words is a trigram, and so on. We might use multiple n-grams instead of just unigrams to extract phrases that we might otherwise miss.

In [80]:
from nltk.util import ngrams

def extract_ngrams(post, num):
    n_grams = ngrams(nltk.word_tokenize(post), num)
    return [ ' '.join(grams) for grams in n_grams]

In [81]:
# unigrams
print(extract_ngrams(cleaned_post, 1))

['i', 'made', 'this', 'boa', 'cosplay', 'only', 'for', 'fun', 'but', 'know', 'i', 'rly', 'love', 'it', '!', 'i', 'want', 'to', 'make', 'in', 'the', 'future', 'more', 'characters', 'but', 'i', 'think', 'is', 'a', 'good', 'start', '!', '💜', '@', 'tsudere_']


In [82]:
# bigrams
print(extract_ngrams(cleaned_post, 2))

['i made', 'made this', 'this boa', 'boa cosplay', 'cosplay only', 'only for', 'for fun', 'fun but', 'but know', 'know i', 'i rly', 'rly love', 'love it', 'it !', '! i', 'i want', 'want to', 'to make', 'make in', 'in the', 'the future', 'future more', 'more characters', 'characters but', 'but i', 'i think', 'think is', 'is a', 'a good', 'good start', 'start !', '! 💜', '💜 @', '@ tsudere_']


In [83]:
# trigrams
print(extract_ngrams(cleaned_post, 3))

['i made this', 'made this boa', 'this boa cosplay', 'boa cosplay only', 'cosplay only for', 'only for fun', 'for fun but', 'fun but know', 'but know i', 'know i rly', 'i rly love', 'rly love it', 'love it !', 'it ! i', '! i want', 'i want to', 'want to make', 'to make in', 'make in the', 'in the future', 'the future more', 'future more characters', 'more characters but', 'characters but i', 'but i think', 'i think is', 'think is a', 'is a good', 'a good start', 'good start !', 'start ! 💜', '! 💜 @', '💜 @ tsudere_']


# Bag-Of-words Analysis

Bag-of-words is a way of representing texts as a 'bag' of terms that appear in the corpus. Dcouments are represented as vectors corresponding to terms that contain 0/1 if the term is not present/present in the document or the vectors contain the amount of times the term appears in the document.

In [84]:
def remove_stopwords2(post): # we want to pass in the tokenized post
    post_no_stop_words = ' '.join([t for t in post.split() if t not in updated_stopwords])
    return post_no_stop_words

In [85]:
# drop rows with nothing in the content
df2 = df.dropna(subset='content')

# initial corpus is just our text from the posts
corpus = df2['content']

# clean the corpus content
corpus_cleaned = corpus.apply(clean_text)

# remove stop_words
corpus_cleaned = corpus.apply(remove_stopwords2)

## Count Vectorizer

Lucky for us, the [scitkit-learn Python library](https://scikit-learn.org/) allows us to do a lot of the cleaning through a [Count Vectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) object.

In [86]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

vectors = vectorizer.fit_transform(corpus_cleaned)

In [93]:
print(vectorizer.vocabulary_)

{'one': 9062, 'piece': 9585, 'episode': 4908, '1101': 116, 'the': 12657, 'strongest': 12163, 'form': 5600, 'humanity': 6641, 'seraphim': 11276, 'powers': 9811, 'watch': 13718, 'now': 8892, 'streaming': 12132, 'site': 11581, 'status': 12035, 'crunchyroll': 3722, 'https': 6629, 'www': 14049, 'com': 3257, 'series': 11281, 'grmg8zqzr': 6144, 'online': 9081, 'chapters': 2986, 'adapted': 1326, 'preview': 9901, '1102': 117, 'http': 6628, 'fujitv': 5731, 'co': 3195, 'jp': 7318, 'b_hp': 2034, 'onepiece': 9067, 'index': 6916, 'html': 6627, 'don': 4404, 'forget': 5590, 'check': 3016, 'official': 9011, 'discord': 4250, 'server': 11294, 'gg': 5916, 'discuss': 4259, 'live': 7828, 'fans': 5270, 'chapter': 2985, '1113': 129, 'around': 1784, 'corner': 3558, 'perfect': 9481, 'time': 12789, 'leave': 7684, 'thoughts': 12729, 'comments': 3290, 'upcoming': 13341, 'this': 12717, 'thread': 12734, 'place': 9632, 'talk': 12487, 'unconfirmed': 13203, 'spoilers': 11934, 'hints': 6508, 'reactions': 10266, 'given':

In [94]:
print(vectors.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [95]:
word_vect_df = pd.DataFrame(data=vectors.toarray(), columns=vectorizer.get_feature_names_out())

In [96]:
word_vect_df.sample(10)

00  000  0001b8f5aa913b8e94a662501e2efbecdb41a17a  001  \
1480   0    0                                         0    0   
646    0    0                                         0    0   
1004   0    0                                         0    0   
845    0    0                                         0    0   
960    0    0                                         0    0   
14     0    0                                         0    0   
241    0    0                                         0    0   
947    0    0                                         0    0   
1664   0    0                                         0    0   
540    0    0                                         0    0   

      003c12dc62a0b07e20af7ea17db79ab45998a64b  \
1480                                         0   
646                                          0   
1004                                         0   
845                                          0   
960                                          0   
14                                           0   
241                                          0   
947                                          0   
1664                                         0   
540                                          0   

      0082291fb3f5f8a7f74f1f3c307b6af53b809ff9  \
1480                                         0   
646                                          0   
1004                                         0   
845                                          0   
960                                          0   
14                                           0   
241                                          0   
947                                          0   
1664                                         0   
540                                          0   

      00adea084ae8fb421196fdbad4667cd2afcc6ed5  \
1480                                         0   
646                                          0   
1004                                         0   
845                                          0   
960                                          0   
14                                           0   
241                                          0   
947                                          0   
1664                                         0   
540                                          0   

      00ccd4bf6f7bf5f7db62a9fd8bece7461712008f  \
1480                                         0   
646                                          0   
1004                                         0   
845                                          0   
960                                          0   
14                                           0   
241                                          0   
947                                          0   
1664                                         0   
540                                          0   

      010c835ff1e9fa4f7ee3ec9bb1c175a510de2d9c  \
1480                                         0   
646                                          0   
1004                                         0   
845                                          0   
960                                          0   
14                                           0   
241                                          0   
947                                          0   
1664                                         0   
540                                          0   

      01a8e2febd180a9b826980e2ee2453301ae3befe  ...  𝘿𝙧𝙚𝙖𝙢𝙨  𝙂𝙤𝙙  𝙄𝙣𝙠  𝙉𝙞𝙜𝙝𝙩  \
1480                                         0  ...       0    0    0      0   
646                                          0  ...       0    0    0      0   
1004                                         0  ...       0    0    0      0   
845                                          0  ...       0    0    0      0   
960                                          0  ...       0    0    0      0   
14                                           0  ...       0    0  

Since the Count Vectorizer returns to us all words that appear in a corpus, there will probably be a lot of words that we are not interested since they either show up too much or are too infrequent to be informative. We can change some of the parameters of the Count Vectorizer to remove less informative terms.

In [102]:
vectorizer2 = CountVectorizer(
    max_df = 0.95,
    min_df = 0.1
)

vectors2 = vectorizer2.fit_transform(corpus_cleaned)

word_vect_df2 = pd.DataFrame(data=vectors2.toarray(), columns=vectorizer2.get_feature_names_out())

In [103]:
word_vect_df2.sample(10)

and  but  could  first  fruit  get  he  https  it  know  ...  the  \
751     0    0      0      0      0    0   0      0   0     0  ...    0   
977     1    0      0      1      0    0   0      0   2     1  ...    1   
1444    1    3      0      1      2    0   2      0   0     0  ...    0   
570     0    0      0      0      0    0   0      0   0     1  ...    0   
1059    0    0      0      0      0    0   0      0   0     0  ...    0   
1387    0    1      0      0      0    0   1      0   1     0  ...    0   
144     0    0      1      0      0    0   0      2   1     1  ...    1   
273     0    0      3      0      0    0   0      1   1     0  ...    0   
243     0    0      1      0      0    0   0      0   0     0  ...    0   
1171    0    1      0      0      1    0   0      0   0     0  ...    0   

      think  this  time  ve  way  we  what  world  would  
751       0     0     0   0    0   0     0      0      0  
977       0     1     0   1    0   1     0      1      3  
1444      1     0     0   0    2   0     0      0      0  
570       0     0     0   0    0   0     0      0      0  
1059      0     1     0   0    0   0     0      0      0  
1387      0     0     0   0    0   0     0      0      0  
144       0     1     1   1    0   1     0      0      0  
273       0     0     0   1    0   1     1      0      0  
243       1     0     0   0    0   0     0      0      0  
1171      0     1     0   0    1   0     0      0      0  

[10 rows x 33 columns]

In [104]:
# saves dataset to same folder as this Jupyter Notebook
# change name to reflect whichever subreddit you used
word_vect_df2.to_csv("new.csv", index=False, encoding='UTF-8')

## Looking at the top Word Counts

In [105]:
word_vect_df2.sum(axis=0).sort_values(ascending=False).head(20)

it        1397
one       1212
luffy     1101
like       990
the        861
https      794
would      762
think      709
he         632
fruit      558
world      555
piece      535
know       529
could      523
people     512
this       457
that       436
see        425
and        398
time       394
dtype: int64

### TFIDF Vectorizer

We can also use [TF-IDF](https://www.learndatasci.com/glossary/tf-idf-term-frequency-inverse-document-frequency/#:~:text=Term%20Frequency%20%2D%20Inverse%20Document%20Frequency%20(TF%2DIDF)%20is,%2C%20relative%20to%20a%20corpus) to extract term importance from the documents instead of simply looking at the term counts. It measures the importance of a term within a document relative to the corpus.

In [106]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(
    max_df = 0.9,
    min_df = 0.1)
tfidf_vectors = tfidf_vect.fit_transform(corpus_cleaned)

In [107]:
print(tfidf_vect.vocabulary_)

{'one': 15, 'piece': 17, 'the': 23, 'https': 7, 'time': 26, 'this': 25, 'people': 16, 'luffy': 11, 'like': 10, 'much': 13, 've': 27, 'fruit': 4, 'make': 12, 'get': 5, 'what': 30, 'so': 21, 'way': 28, 'we': 29, 'think': 24, 'he': 6, 'it': 8, 'know': 9, 'since': 20, 'that': 22, 'would': 32, 'and': 0, 'first': 3, 'could': 2, 'but': 1, 'see': 19, 'world': 31, 'oda': 14, 'really': 18}


In [108]:
print(tfidf_vectors.toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.3366119  0.57924122]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [109]:
tfidf_df = pd.DataFrame(data=tfidf_vectors.toarray(), columns=tfidf_vect.get_feature_names_out())

In [110]:
tfidf_df.sample(10)

and  but     could     first     fruit       get        he  https  \
1575  0.162515  0.0  0.000000  0.000000  0.336661  0.000000  0.150571    0.0   
1114  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.000000    0.0   
1211  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.000000    0.0   
134   0.000000  0.0  0.000000  0.000000  0.000000  0.000000  1.000000    0.0   
1572  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.000000    0.0   
1179  0.000000  0.0  0.377667  0.000000  0.000000  0.000000  0.000000    0.0   
1452  0.000000  0.0  0.541727  0.000000  0.000000  0.000000  0.000000    0.0   
1489  0.000000  0.0  0.000000  0.321244  0.000000  0.000000  0.000000    0.0   
890   0.524050  0.0  0.000000  0.000000  0.542803  0.250831  0.242768    0.0   
1562  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.000000    0.0   

            it      know  ...       the     think  this      time   ve  \
1575  0.236259  0.000000  ...  0.000000  0.128208   0.0  0.000000  0.0   
1114  0.582209  0.000000  ...  0.000000  0.000000   0.0  0.000000  0.0   
1211  0.000000  0.496969  ...  0.000000  0.000000   0.0  0.000000  0.0   
134   0.000000  0.000000  ...  0.000000  0.000000   0.0  0.000000  0.0   
1572  0.000000  0.000000  ...  1.000000  0.000000   0.0  0.000000  0.0   
1179  0.000000  0.703464  ...  0.000000  0.000000   0.0  0.000000  0.0   
1452  0.000000  0.000000  ...  0.000000  0.000000   0.0  0.000000  0.0   
1489  0.000000  0.249435  ...  0.509084  0.000000   0.0  0.000000  0.0   
890   0.380924  0.000000  ...  0.000000  0.000000   0.0  0.246865  0.0   
1562  0.000000  0.000000  ...  0.000000  0.000000   0.0  0.000000  0.0   

           way   we  what     world  would  
1575  0.000000  0.0   0.0  0.619784    0.0  
1114  0.000000  0.0   0.0  0.000000    0.0  
1211  0.000000  0.0   0.0  0.000000    0.0  
134   0.000000  0.0   0.0  0.000000    0.0  
1572  0.000000  0.0   0.0  0.000000    0.0  
1179  0.000000  0.0   0.0  0.000000    0.0  
1452  0.000000  0.0   0.0  0.000000    0.0  
1489  0.299287  0.0   0.0  0.000000    0.0  
890   0.000000  0.0   0.0  0.249822    0.0  
1562  0.000000  0.0   0.0  0.000000    0.0  

[10 rows x 33 columns]

In [111]:
# saves dataset to same folder as this Jupyter Notebook
# change name to reflect whichever subreddit you used
tfidf_df.to_csv("XXX.csv", index=False, encoding='UTF-8')

## Why might weight for these terms be helpful for text analysis?